

# Only runs when there"s a new version released (i.e. changes should be versioned really)
on:
  push:
    tags:
      - "v*"


jobs:

  build:
    name: "Vite build"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm # or pnpm / yarn
      - name: Install dependencies
        run: npm ci # or pnpm install / yarn install / bun install

      - name: Build with Vite
        run: npm run build-app

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: dist

