

# Only runs when there"s a new version released (i.e. changes should be versioned really)
on:
  push:
    tags:
      - "v*"


jobs:

  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm # or pnpm / yarn
      - name: Install dependencies
        run: npm ci # or pnpm install / yarn install / bun install

      - name: Build with Vite
        run: npm run build-app

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: master
          production-deploy: true
          netlify-config-path: ./dist/netlify.toml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
